import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Gojek SuperApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://db.onlinewebfonts.com/c/8b59d4b47037b08d452d8cb659cc2d53?family=Maison+Neue+Light"
          rel="stylesheet"
        />
        <link
          href="https://db.onlinewebfonts.com/c/b596fe7f763c7633f489a1acdbb13c70?family=Maison+Neue+Demi"
          rel="stylesheet"
        />
        <link
          href="https://db.onlinewebfonts.com/c/a6a787f8616df7d0847ed764ff81d724?family=Maison+Neue+Extended+Extra+Bold"
          rel="stylesheet"
        />
      </head>
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
